#!/bin/bash

set -x 

cd $(dirname $0)/..

echo "B374A26A71490437AA024E4FADD5B49" > /etc/ssl/private/test_key

./bin/secrets-api -d server --enc-key-path /etc/ssl/private/test_key &

cd integration
python --version

find -depth -name __pycache__ -o -name "*.pyc" -exec rm -rf {} \;
if [ -z "$NO_TEST" ]; then
    tox "$@"
fi
